CVsetts <- list(EstimationTask(metrics=c('mad', 'mse', 'mae_phi',
                                         'mse_phi', 'rmse_phi', 'ubaF1', 'ubaF05', 'ubaF2',
                                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
                               evaluator="eval.stats", 
                               evaluator.pars=list(thr.rel=thr.rel,
                                                   method=PCS[[1]][[1]][[1]], 
                                                   npts=PCS[[1]][[1]][[2]], 
                                                   control.pts=PCS[[1]][[1]][[3]], 
                                                   ymin=PCS[[1]][[2]][[1]], 
                                                   ymax=PCS[[1]][[2]][[2]], 
                                                   tloss=PCS[[1]][[2]][[3]], 
                                                   epsilon=PCS[[1]][[2]][[4]],
                                                   p=0.5),
                               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi',
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec',  'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[2]][[1]][[1]], 
                                   npts=PCS[[2]][[1]][[2]], 
                                   control.pts=PCS[[2]][[1]][[3]], 
                                   ymin=PCS[[2]][[2]][[1]], 
                                   ymax=PCS[[2]][[2]][[2]], 
                                   tloss=PCS[[2]][[2]][[3]], 
                                   epsilon=PCS[[2]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi',
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[3]][[1]][[1]], 
                                   npts=PCS[[3]][[1]][[2]], 
                                   control.pts=PCS[[3]][[1]][[3]], 
                                   ymin=PCS[[3]][[2]][[1]], 
                                   ymax=PCS[[3]][[2]][[2]], 
                                   tloss=PCS[[3]][[2]][[3]], 
                                   epsilon=PCS[[3]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi', 
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[4]][[1]][[1]], 
                                   npts=PCS[[4]][[1]][[2]], 
                                   control.pts=PCS[[4]][[1]][[3]], 
                                   ymin=PCS[[4]][[2]][[1]], 
                                   ymax=PCS[[4]][[2]][[2]], 
                                   tloss=PCS[[4]][[2]][[3]], 
                                   epsilon=PCS[[4]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi',
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[5]][[1]][[1]], 
                                   npts=PCS[[5]][[1]][[2]], 
                                   control.pts=PCS[[5]][[1]][[3]], 
                                   ymin=PCS[[5]][[2]][[1]], 
                                   ymax=PCS[[5]][[2]][[2]], 
                                   tloss=PCS[[5]][[2]][[3]], 
                                   epsilon=PCS[[5]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi', 
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[6]][[1]][[1]], 
                                   npts=PCS[[6]][[1]][[2]], 
                                   control.pts=PCS[[6]][[1]][[3]], 
                                   ymin=PCS[[6]][[2]][[1]], 
                                   ymax=PCS[[6]][[2]][[2]], 
                                   tloss=PCS[[6]][[2]][[3]], 
                                   epsilon=PCS[[6]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi',
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[7]][[1]][[1]], 
                                   npts=PCS[[7]][[1]][[2]], 
                                   control.pts=PCS[[7]][[1]][[3]], 
                                   ymin=PCS[[7]][[2]][[1]], 
                                   ymax=PCS[[7]][[2]][[2]], 
                                   tloss=PCS[[7]][[2]][[3]], 
                                   epsilon=PCS[[7]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi',
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[8]][[1]][[1]], 
                                   npts=PCS[[8]][[1]][[2]], 
                                   control.pts=PCS[[8]][[1]][[3]], 
                                   ymin=PCS[[8]][[2]][[1]], 
                                   ymax=PCS[[8]][[2]][[2]], 
                                   tloss=PCS[[8]][[2]][[3]], 
                                   epsilon=PCS[[8]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi',
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[9]][[1]][[1]], 
                                   npts=PCS[[9]][[1]][[2]], 
                                   control.pts=PCS[[9]][[1]][[3]], 
                                   ymin=PCS[[9]][[2]][[1]], 
                                   ymax=PCS[[9]][[2]][[2]], 
                                   tloss=PCS[[9]][[2]][[3]], 
                                   epsilon=PCS[[9]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi',
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[10]][[1]][[1]], 
                                   npts=PCS[[10]][[1]][[2]], 
                                   control.pts=PCS[[10]][[1]][[3]], 
                                   ymin=PCS[[10]][[2]][[1]], 
                                   ymax=PCS[[10]][[2]][[2]], 
                                   tloss=PCS[[10]][[2]][[3]], 
                                   epsilon=PCS[[10]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi',
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[11]][[1]][[1]], 
                                   npts=PCS[[11]][[1]][[2]], 
                                   control.pts=PCS[[11]][[1]][[3]], 
                                   ymin=PCS[[11]][[2]][[1]], 
                                   ymax=PCS[[11]][[2]][[2]], 
                                   tloss=PCS[[11]][[2]][[3]], 
                                   epsilon=PCS[[11]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi',
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[12]][[1]][[1]], 
                                   npts=PCS[[12]][[1]][[2]], 
                                   control.pts=PCS[[12]][[1]][[3]], 
                                   ymin=PCS[[12]][[2]][[1]], 
                                   ymax=PCS[[12]][[2]][[2]], 
                                   tloss=PCS[[12]][[2]][[3]], 
                                   epsilon=PCS[[12]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi',
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[13]][[1]][[1]], 
                                   npts=PCS[[13]][[1]][[2]], 
                                   control.pts=PCS[[13]][[1]][[3]], 
                                   ymin=PCS[[13]][[2]][[1]], 
                                   ymax=PCS[[13]][[2]][[2]], 
                                   tloss=PCS[[13]][[2]][[3]], 
                                   epsilon=PCS[[13]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi', 
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[14]][[1]][[1]], 
                                   npts=PCS[[14]][[1]][[2]], 
                                   control.pts=PCS[[14]][[1]][[3]], 
                                   ymin=PCS[[14]][[2]][[1]], 
                                   ymax=PCS[[14]][[2]][[2]], 
                                   tloss=PCS[[14]][[2]][[3]], 
                                   epsilon=PCS[[14]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi', 
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[15]][[1]][[1]], 
                                   npts=PCS[[15]][[1]][[2]], 
                                   control.pts=PCS[[15]][[1]][[3]], 
                                   ymin=PCS[[15]][[2]][[1]], 
                                   ymax=PCS[[15]][[2]][[2]], 
                                   tloss=PCS[[15]][[2]][[3]], 
                                   epsilon=PCS[[15]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi', 
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[16]][[1]][[1]], 
                                   npts=PCS[[16]][[1]][[2]], 
                                   control.pts=PCS[[16]][[1]][[3]], 
                                   ymin=PCS[[16]][[2]][[1]], 
                                   ymax=PCS[[16]][[2]][[2]], 
                                   tloss=PCS[[16]][[2]][[3]], 
                                   epsilon=PCS[[16]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi', 
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[17]][[1]][[1]], 
                                   npts=PCS[[17]][[1]][[2]], 
                                   control.pts=PCS[[17]][[1]][[3]], 
                                   ymin=PCS[[17]][[2]][[1]], 
                                   ymax=PCS[[17]][[2]][[2]], 
                                   tloss=PCS[[17]][[2]][[3]], 
                                   epsilon=PCS[[17]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi', 
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[18]][[1]][[1]], 
                                   npts=PCS[[18]][[1]][[2]], 
                                   control.pts=PCS[[18]][[1]][[3]], 
                                   ymin=PCS[[18]][[2]][[1]], 
                                   ymax=PCS[[18]][[2]][[2]], 
                                   tloss=PCS[[18]][[2]][[3]], 
                                   epsilon=PCS[[18]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi', 
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[19]][[1]][[1]], 
                                   npts=PCS[[19]][[1]][[2]], 
                                   control.pts=PCS[[19]][[1]][[3]], 
                                   ymin=PCS[[19]][[2]][[1]], 
                                   ymax=PCS[[19]][[2]][[2]], 
                                   tloss=PCS[[19]][[2]][[3]], 
                                   epsilon=PCS[[19]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
),
EstimationTask(metrics=c('mad', 'mse', 'mae_phi', 
                         'mse_phi', 'rmse_phi', 'ubaF1','ubaF05','ubaF2',
                         'ubaprec', 'ubarec', 'MU', 'NMU'), 
               evaluator="eval.stats", 
               evaluator.pars=list(thr.rel=thr.rel,
                                   method=PCS[[20]][[1]][[1]], 
                                   npts=PCS[[20]][[1]][[2]], 
                                   control.pts=PCS[[20]][[1]][[3]], 
                                   ymin=PCS[[20]][[2]][[1]], 
                                   ymax=PCS[[20]][[2]][[2]], 
                                   tloss=PCS[[20]][[2]][[3]], 
                                   epsilon=PCS[[20]][[2]][[4]],
                                   p=0.5),
               method=CV(nReps=2,nFolds=10,strat=TRUE)
)
)
